/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import dataBase.configdb_2110010302;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator 10
 */
public class frameSuratKeluar extends javax.swing.JFrame {
    configdb_2110010302 obj;
    
    public void tampilDataSKeluar(){
        String[] JudulKolom = {"kode surat","tgl keluar","no","tujuan", "perihal", "scan", "tgl input", "kode admin"}; //kolom yang akan di tampilkan
        int[] lebar ={50, 100, 50, 150, 150, 75, 100, 50}; //lebar masing-masing kolom
        String query = "SELECT * FROM tbl_suratkeluar";
        obj.JudulJTable(jTableSKeluar, JudulKolom); //judul kolom
        obj.tampilTable(JudulKolom, query, jTableSKeluar); //isi tabel
        obj.LebarJtable(jTableSKeluar, lebar); //lebar kolom
    }
    
    public frameSuratKeluar() {
        initComponents();
        this.setLocationRelativeTo(null);
        obj = new configdb_2110010302();
        tampilDataSKeluar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_tujuan_suratkeluar = new javax.swing.JTextField();
        txt_kd_suratkeluar = new javax.swing.JTextField();
        txt_no_suratkeluar = new javax.swing.JTextField();
        txt_scan_suratkeluar = new javax.swing.JTextField();
        txt_kd_admin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSKeluar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_perihal_suratkeluar = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_tgl_suratkeluar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("kode surat keluar");

        jLabel2.setText("tanggal");

        jLabel3.setText("nomor surat keluar");

        jLabel4.setText("tujuan");

        jLabel5.setText("perihal");

        jLabel6.setText("scan");

        jLabel8.setText("kode admin");

        txt_tujuan_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tujuan_suratkeluarActionPerformed(evt);
            }
        });

        txt_kd_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kd_suratkeluarActionPerformed(evt);
            }
        });

        txt_no_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_suratkeluarActionPerformed(evt);
            }
        });

        txt_scan_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_scan_suratkeluarActionPerformed(evt);
            }
        });

        txt_kd_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kd_adminActionPerformed(evt);
            }
        });

        jTableSKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kode", "tanggal", "nomor surat", "tujuan", "perihal", "scan file", "kode admin"
            }
        ));
        jTableSKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSKeluarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSKeluar);

        txta_perihal_suratkeluar.setColumns(20);
        txta_perihal_suratkeluar.setRows(5);
        jScrollPane2.setViewportView(txta_perihal_suratkeluar);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel13.setText("*dalam format tahun-bulan-tanggal (tttt-bb-hh)");

        txt_tgl_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tgl_suratkeluarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel14.setText("*isi dengan direktori surat");

        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("CARI DATA");

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kd_admin)
                                    .addComponent(txt_scan_suratkeluar)
                                    .addComponent(txt_tujuan_suratkeluar)
                                    .addComponent(txt_no_suratkeluar)
                                    .addComponent(txt_kd_suratkeluar)
                                    .addComponent(txt_tgl_suratkeluar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtCari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_kd_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tgl_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_no_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_tujuan_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_scan_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_kd_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tujuan_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tujuan_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tujuan_suratkeluarActionPerformed

    private void txt_kd_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kd_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kd_suratkeluarActionPerformed

    private void txt_no_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_suratkeluarActionPerformed

    private void txt_scan_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_scan_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_scan_suratkeluarActionPerformed

    private void txt_kd_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kd_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kd_adminActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            String[] FieldTabelnya ={"kd_suratkeluar", "tgl_suratkeluar", "no_suratkeluar", "tujuan_suratkeluar", "perihal_suratkeluar", "scan_suratkeluar", "tgl_inputsuratkeluar", "kd_admin" };
            String[] Isitabelnya = {txt_kd_suratkeluar.getText(), txt_tgl_suratkeluar.getText(), txt_no_suratkeluar.getText(), txt_tujuan_suratkeluar.getText(), txta_perihal_suratkeluar.getText(), txt_scan_suratkeluar.getText(), txt_kd_admin.getText()};
            String NamaTabel = "tbl_suratkeluar";
            if (txt_kd_suratkeluar.getText().isEmpty()){ //jika Id kosong, tampilkan pesan
                JOptionPane.showMessageDialog(this, "Kode Surat Keluar Belum Di Isi!");
                txt_kd_suratkeluar.requestFocus();
            } else if (txt_tgl_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal Keluar Surat Belum Di Isi!");
                txt_tgl_suratkeluar.requestFocus();
            } else if (txt_no_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nomor Surat Keluar Belum Di Isi!");
                txt_no_suratkeluar.requestFocus();
            } else if (txt_tujuan_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tujuan Surat Belum Di Isi!");
                txt_tujuan_suratkeluar.requestFocus();
            } else if (txta_perihal_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Perihal Surat Belum Di Isi!");
                txta_perihal_suratkeluar.requestFocus();
            } else if (txt_scan_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Scan Surat Belum Di Isi!");
                txt_scan_suratkeluar.requestFocus();
            } else if (txt_kd_admin.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Kode Admin Belum Di Isi!");
                txt_kd_admin.requestFocus();
            } else if(obj.duplikasiKey(NamaTabel, "kd_suratkeluar", txt_kd_suratkeluar.getText())){
                JOptionPane.showMessageDialog(this, "Kode Surat Keluar sudah terdaftar");
                try {
                    Statement stm = obj.getKoneksi().createStatement();
                    ResultSet rslt = stm.executeQuery("SELECT * FROM tbl_suratmasuk");
                    rslt.next();
                    txt_kd_suratkeluar.setText(rslt.getString(2));
                    txt_tgl_suratkeluar.setText(rslt.getString(3));
                    txt_no_suratkeluar.setText(rslt.getString(4));
                    txt_tujuan_suratkeluar.setText(rslt.getString(5));
                    txta_perihal_suratkeluar.setText(rslt.getString(6));
                    txt_scan_suratkeluar.setText(rslt.getString(7));
                    txt_kd_admin.setText(rslt.getString(8));
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e.toString());
                }
            } else {
                obj.simpanDBAuto(NamaTabel, FieldTabelnya, Isitabelnya);
                tampilDataSKeluar();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Tambahkan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            if ((txt_kd_suratkeluar.getText().isEmpty()) &&  (txt_tgl_suratkeluar.getText().isEmpty()) &&  (txt_no_suratkeluar.getText().isEmpty()) &&  (txt_tujuan_suratkeluar.getText().isEmpty()) &&  (txta_perihal_suratkeluar.getText().isEmpty()) &&  (txt_scan_suratkeluar.getText().isEmpty()) &&  (txt_kd_admin.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu!");
            } else {
                String[] FieldTabelnya ={"tgl_suratkeluar", "no_suratkeluar", "tujuan_suratkeluar", "perihal_suratkeluar", "scan_suratkeluar", "tgl_inputsuratkeluar", "kd_admin" };
                String[] Isitabelnya = {txt_tgl_suratkeluar.getText(), txt_no_suratkeluar.getText(), txt_tujuan_suratkeluar.getText(), txta_perihal_suratkeluar.getText(), txt_scan_suratkeluar.getText(), txt_kd_admin.getText()};
                String NamaTabel = "tbl_suratkeluar";
                String kd_key = txt_kd_suratkeluar.getText();
                obj.UbahDBAuto(NamaTabel, "kd_suratkeluar", kd_key, FieldTabelnya, Isitabelnya);
                tampilDataSKeluar();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Ubah!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            if ((txt_kd_suratkeluar.getText().isEmpty()) &&  (txt_tgl_suratkeluar.getText().isEmpty()) &&  (txt_no_suratkeluar.getText().isEmpty()) &&  (txt_tujuan_suratkeluar.getText().isEmpty()) &&  (txta_perihal_suratkeluar.getText().isEmpty()) &&  (txt_scan_suratkeluar.getText().isEmpty()) &&  (txt_kd_admin.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Akan Di Hapus Terlebih Dahulu!");
            }else{
                String NamaTabel = "tbl_suratkeluar";
                String kd_key = txt_kd_suratkeluar.getText();
                obj.HapusDBAuto(NamaTabel, "kd_suratmasuk", kd_key);
                tampilDataSKeluar();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus!");
            }
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txt_tgl_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tgl_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tgl_suratkeluarActionPerformed

    private void jTableSKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSKeluarMouseClicked
       int i = jTableSKeluar.getSelectedRow();
       String kd_suratmasuk = jTableSKeluar.getValueAt(i, 0).toString();
       String tgl_suratkeluar = jTableSKeluar.getValueAt(i, 1).toString();
       String no_suratkeluar = jTableSKeluar.getValueAt(i, 2).toString();
       String tujuan_suratkeluar = jTableSKeluar.getValueAt(i, 3).toString();       
       String perihal_suratkeluar = jTableSKeluar.getValueAt(i, 4).toString();
       String scan_suratkeluar = jTableSKeluar.getValueAt(i, 5).toString();
       String tgl_inputsuratkeluar = jTableSKeluar.getValueAt(i, 6).toString();
       String kd_admin = jTableSKeluar.getValueAt(i, 7).toString();
       
       txt_kd_suratkeluar.setText(kd_suratmasuk);
       txt_tgl_suratkeluar.setText(tgl_suratkeluar);
       txt_no_suratkeluar.setText(no_suratkeluar);
       txt_tujuan_suratkeluar.setText(tujuan_suratkeluar);
       txta_perihal_suratkeluar.setText(perihal_suratkeluar);
       txt_scan_suratkeluar.setText(scan_suratkeluar);
       txt_kd_admin.setText(kd_admin);
       
       
    }//GEN-LAST:event_jTableSKeluarMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String clear = "";

        txt_kd_suratkeluar.setText(clear);
        txt_tgl_suratkeluar.setText(clear);
        txt_no_suratkeluar.setText(clear);
        txt_tujuan_suratkeluar.setText(clear);
        txta_perihal_suratkeluar.setText(clear);
        txt_scan_suratkeluar.setText(clear);
        txt_kd_admin.setText(clear);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        try {
            String cari = txtCari.getText();
            String searchQuery = "SELECT * FROM tbl_suratkeluar WHERE kd_suratkeluar LIKE '%" + cari + "%' OR " +
                                "no_suratkeluar LIKE '%" + cari + "%' OR " +
                                "tujuan_suratkeluar LIKE '%" + cari + "%' OR " +
                                "perihal_suratkeluar LIKE '%" + cari + "%' OR " +
                                "scan_suratkeluar LIKE '%" + cari + "%' OR " +
                                "kd_admin LIKE '%" + cari + "%'";

            String[] JudulKolom = {"kode surat","tgl keluar","no","tujuan", "perihal", "scan", "tgl input", "kode admin"}; //kolom yang akan di tampilkan
            int[] lebar ={50, 100, 50, 150, 150, 75, 100, 50}; //lebar masing-masing kolom
            obj.JudulJTable(jTableSKeluar, JudulKolom); //judul kolom
            obj.tampilTable(JudulKolom, searchQuery, jTableSKeluar); //isi tabel
            obj.LebarJtable(jTableSKeluar, lebar); //lebar kolom

        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameSuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameSuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameSuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameSuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameSuratKeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableSKeluar;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txt_kd_admin;
    private javax.swing.JTextField txt_kd_suratkeluar;
    private javax.swing.JTextField txt_no_suratkeluar;
    private javax.swing.JTextField txt_scan_suratkeluar;
    private javax.swing.JTextField txt_tgl_suratkeluar;
    private javax.swing.JTextField txt_tujuan_suratkeluar;
    private javax.swing.JTextArea txta_perihal_suratkeluar;
    // End of variables declaration//GEN-END:variables
}
