/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dataBase.koneksi;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator 10
 */
public class frameSuratKeluar extends javax.swing.JFrame {

    koneksi objekku;
    DefaultTableModel modelTabelSKeluar;
    
    public frameSuratKeluar() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekku = new koneksi();
        modelTabelSKeluar = new DefaultTableModel();
        jTableSKeluar.setModel(modelTabelSKeluar);
        
        modelTabelSKeluar.addColumn("kd_suratkeluar");
        modelTabelSKeluar.addColumn("tgl_suratkeluar");
        modelTabelSKeluar.addColumn("no_suratkeluar");
        modelTabelSKeluar.addColumn("tujuan_suratkeluar");
        modelTabelSKeluar.addColumn("perihal_suratkeluar");
        modelTabelSKeluar.addColumn("scan_suratkeluar");
        modelTabelSKeluar.addColumn("tgl_inputsuratkeluar");
        modelTabelSKeluar.addColumn("kd_admin");       
        
        loadTabelSKeluar();
    }
    
    void loadTabelSKeluar(){
        try {
            String sql = "SELECT * FROM tbl_suratkeluar";
            PreparedStatement kueri = objekku.konekDB.prepareStatement(sql);
            ResultSet data = kueri.executeQuery();
            
            while(data.next()){
                Object[] baris = new Object[8];
                baris[0] = data.getString("kd_suratkeluar");
                baris[1] = data.getString("tgl_suratkeluar");
                baris[2] = data.getString("no_suratkeluar");
                baris[3] = data.getString("tujuan_suratkeluar");
                baris[4] = data.getString("perihal_suratkeluar");
                baris[5] = data.getString("scan_suratkeluar");
                baris[6] = data.getString("tgl_inputsuratkeluar");
                baris[7] = data.getString("kd_admin");
            }
        } catch(Exception e) {
            System.out.print(e.getMessage()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_tujuan_suratkeluar = new javax.swing.JTextField();
        txt_kd_suratkeluar = new javax.swing.JTextField();
        txt_no_suratkeluar = new javax.swing.JTextField();
        txt_scan_suratkeluar = new javax.swing.JTextField();
        txt_kd_admin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSKeluar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_perihal_suratkeluar = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_tgl_suratkeluar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("kode surat keluar");

        jLabel2.setText("tanggal");

        jLabel3.setText("nomor surat keluar");

        jLabel4.setText("tujuan");

        jLabel5.setText("perihal");

        jLabel6.setText("scan");

        jLabel8.setText("kode admin");

        txt_tujuan_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tujuan_suratkeluarActionPerformed(evt);
            }
        });

        txt_kd_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kd_suratkeluarActionPerformed(evt);
            }
        });

        txt_no_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_suratkeluarActionPerformed(evt);
            }
        });

        txt_scan_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_scan_suratkeluarActionPerformed(evt);
            }
        });

        txt_kd_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kd_adminActionPerformed(evt);
            }
        });

        jTableSKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kode", "tanggal", "nomor surat", "tujuan", "perihal", "scan file", "kode admin"
            }
        ));
        jScrollPane1.setViewportView(jTableSKeluar);

        txta_perihal_suratkeluar.setColumns(20);
        txta_perihal_suratkeluar.setRows(5);
        jScrollPane2.setViewportView(txta_perihal_suratkeluar);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel13.setText("*dalam format tahun-bulan-tanggal (tttt-bb-hh)");

        txt_tgl_suratkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tgl_suratkeluarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel14.setText("*isi dengan direktori surat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kd_admin)
                                    .addComponent(txt_scan_suratkeluar)
                                    .addComponent(txt_tujuan_suratkeluar)
                                    .addComponent(txt_no_suratkeluar)
                                    .addComponent(txt_kd_suratkeluar)
                                    .addComponent(txt_tgl_suratkeluar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_kd_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tgl_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_no_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_tujuan_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_scan_suratkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_kd_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tujuan_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tujuan_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tujuan_suratkeluarActionPerformed

    private void txt_kd_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kd_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kd_suratkeluarActionPerformed

    private void txt_no_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_suratkeluarActionPerformed

    private void txt_scan_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_scan_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_scan_suratkeluarActionPerformed

    private void txt_kd_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kd_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kd_adminActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TAMBAHKAN DI SINI
        try {
            if (txt_kd_suratkeluar.getText().isEmpty()){ //jika Id kosong, tampilkan pesan
                JOptionPane.showMessageDialog(this, "Kode Surat Keluar Belum Di Isi!");
                txt_kd_suratkeluar.requestFocus();
            } else if (txt_tgl_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tanggal Keluar Surat Belum Di Isi!");
                txt_tgl_suratkeluar.requestFocus();
            } else if (txt_no_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nomor Surat Keluar Belum Di Isi!");
                txt_no_suratkeluar.requestFocus();
            } else if (txt_tujuan_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Tujuan Surat Belum Di Isi!");
                txt_tujuan_suratkeluar.requestFocus();
            } else if (txta_perihal_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Perihal Surat Belum Di Isi!");
                txta_perihal_suratkeluar.requestFocus();
            } else if (txt_scan_suratkeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Scan Surat Belum Di Isi!");
                txt_scan_suratkeluar.requestFocus();
            } else if (txt_kd_admin.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Kode Admin Belum Di Isi!");
            } else {
                String sqlcari = "SELECT * FROM tbl_suratkeluar WHERE kd_suratkeluar = ?";
                PreparedStatement cari = objekku.konekDB.prepareStatement(sqlcari);
                cari.setString(1, txt_kd_suratkeluar.getText());
                ResultSet hasil = cari.executeQuery();
                
                if (hasil.next()){
                    JOptionPane.showMessageDialog(this, "Kode Surat Keluar Sudah Ada!");
                    
                    txt_kd_suratkeluar.setText(hasil.getString("kd_suratkeluar"));
                    txt_tgl_suratkeluar.setText(hasil.getString("tgl_suratkeluar"));
                    txt_no_suratkeluar.setText(hasil.getString("no_suratkeluar"));
                    txt_tujuan_suratkeluar.setText(hasil.getString("tujuan_suratkeluar"));
                    txta_perihal_suratkeluar.setText(hasil.getString("perihal_suratkeluar"));
                    txt_scan_suratkeluar.setText(hasil.getString("scan_suratkeluar"));
                    txt_kd_admin.setText(hasil.getString("kd_admin"));
                } else {
                    String sqlSimpan = "INSERT INTO tbl_suratkeluar (kd_suratkeluar, tgl_suratkeluar, no_suratkeluar, tujuan_suratkeluar, perihal_suratkeluar, scan_suratkeluar, kd_admin) VALUE (?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement kueri = objekku.konekDB.prepareCall(sqlSimpan);
                    
                    kueri.setString(1, txt_kd_suratkeluar.getText());
                    kueri.setString(2, txt_tgl_suratkeluar.getText());
                    kueri.setString(3, txt_no_suratkeluar.getText());
                    kueri.setString(4, txt_tujuan_suratkeluar.getText());
                    kueri.setString(5, txta_perihal_suratkeluar.getText());
                    kueri.setString(6, txt_scan_suratkeluar.getText());
                    kueri.setString(7, txt_kd_admin.getText());

                    kueri.executeUpdate();
                    loadTabelSKeluar();
                    
                    JOptionPane.showMessageDialog(this, "Data Berhasil Di Simpan.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            String sqlUbah = "UPDATE tbl_suratkeluar SET tgl_suratkeluar = ?, no_suratkeluar = ?, tujuan_suratkeluar = ?, perihal_suratkeluar = ?, scan_suratkeluar = ?, kd_admin = ? WHERE kd_suratkeluar = ?";
            PreparedStatement kueri = objekku.konekDB.prepareStatement(sqlUbah);
            
            kueri.setString(7, txt_kd_suratkeluar.getText());
            kueri.setString(1, txt_tgl_suratkeluar.getText());
            kueri.setString(2, txt_no_suratkeluar.getText());
            kueri.setString(3, txt_tujuan_suratkeluar.getText());
            kueri.setString(4, txta_perihal_suratkeluar.getText());
            kueri.setString(5, txt_scan_suratkeluar.getText());
            kueri.setString(6, txt_kd_admin.getText());
            
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Ubah.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            String sqlHapus = "DELETE FROM tbl_suratkeluar WHERE kd_suratkeluar = ?";
            PreparedStatement kueri = objekku.konekDB.prepareStatement(sqlHapus);
            
            kueri.setString(1, txt_kd_suratkeluar.getText());
            
            kueri.executeUpdate();
            loadTabelSKeluar();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txt_tgl_suratkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tgl_suratkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tgl_suratkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameSuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameSuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameSuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameSuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameSuratKeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableSKeluar;
    private javax.swing.JTextField txt_kd_admin;
    private javax.swing.JTextField txt_kd_suratkeluar;
    private javax.swing.JTextField txt_no_suratkeluar;
    private javax.swing.JTextField txt_scan_suratkeluar;
    private javax.swing.JTextField txt_tgl_suratkeluar;
    private javax.swing.JTextField txt_tujuan_suratkeluar;
    private javax.swing.JTextArea txta_perihal_suratkeluar;
    // End of variables declaration//GEN-END:variables
}
