/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import dataBase.koneksi;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator 10
 */
public class frameSppd extends javax.swing.JFrame {
    koneksi objekku;
    DefaultTableModel modelTabelSppd;
    public frameSppd() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekku = new koneksi();
        jTableSppd.setModel(modelTabelSppd);
        
        modelTabelSppd.addColumn("kd_sppd");
        modelTabelSppd.addColumn("no_sppd");
        modelTabelSppd.addColumn("kd_pegawai");
        modelTabelSppd.addColumn("tgl_sppd");
        modelTabelSppd.addColumn("tempat_sppd");
        modelTabelSppd.addColumn("kendaraan_sppd");
        modelTabelSppd.addColumn("biaya_sppd");
        modelTabelSppd.addColumn("tgl_inputsppd");
        modelTabelSppd.addColumn("kd_admin");
        modelTabelSppd.addColumn("scan_sppd");
    }
    
    void loadTableSppd(){
        try {
            String sql = "SELECT * FROM tbl_sppd";
            PreparedStatement kueri = objekku.konekDB.prepareCall(sql);
            ResultSet data = kueri.executeQuery();
            
            while (data.next()){
                Object[] baris = new Object[10];
                baris[0] = data.getString("kd_sppd");
                baris[1] = data.getString("no_sppd");
                baris[2] = data.getString("kd_pegawai");
                baris[3] = data.getString("tgl_sppd");
                baris[4] = data.getString("tempat_sppd");
                baris[5] = data.getString("kendaraan_sppd");
                baris[6] = data.getString("biaya_sppd");
                baris[7] = data.getString("tgl_inputsppd");
                baris[8] = data.getString("kd_admin");
                baris[9] = data.getString("scan_sppd");
                
                modelTabelSppd.addRow(baris);
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_kd_sppd = new javax.swing.JTextField();
        txt_kd_pegawai = new javax.swing.JTextField();
        txt_kendaraan = new javax.swing.JTextField();
        txt_biaya = new javax.swing.JTextField();
        txt_kodeadmin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSppd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_tempat = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txt_scan = new javax.swing.JTextField();
        txt_no_sppd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_tgl_sppd = new javax.swing.JTextField();
        txt_sppd_in = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("kode SPPD");

        jLabel2.setText("nomor SPPD");

        jLabel3.setText("kode pegawai");

        jLabel4.setText("tanggal SPPD");

        jLabel5.setText("tempat SPPD");

        jLabel6.setText("kendaraan SPPD");

        jLabel7.setText("biaya SPPD");

        jLabel8.setText("tanggal input SPPD");

        jLabel9.setText("kode admin");

        jLabel10.setText("scan SPPD");

        txt_kd_sppd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kd_sppdActionPerformed(evt);
            }
        });

        txt_kd_pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kd_pegawaiActionPerformed(evt);
            }
        });

        txt_kendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kendaraanActionPerformed(evt);
            }
        });

        txt_biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_biayaActionPerformed(evt);
            }
        });

        txt_kodeadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeadminActionPerformed(evt);
            }
        });

        jTableSppd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kode", "nomor", "kode pegawai", "tanggal", "tempat", "kendaraan", "biaya", "tanggal input", "kode admin", "scan"
            }
        ));
        jTableSppd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSppdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSppd);

        txta_tempat.setColumns(20);
        txta_tempat.setRows(5);
        jScrollPane2.setViewportView(txta_tempat);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txt_scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_scanActionPerformed(evt);
            }
        });

        txt_no_sppd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_sppdActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel13.setText("*dalam format tahun-bulan-tanggal (tttt-bb-hh)");

        txt_tgl_sppd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tgl_sppdActionPerformed(evt);
            }
        });

        txt_sppd_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sppd_inActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel14.setText("*dalam format tahun-bulan-tanggal (tttt-bb-hh)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(81, 81, 81)
                                .addComponent(txt_scan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(txt_kodeadmin)
                                            .addComponent(txt_biaya)
                                            .addComponent(txt_kendaraan)
                                            .addComponent(txt_kd_pegawai)
                                            .addComponent(txt_kd_sppd)
                                            .addComponent(txt_no_sppd, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_sppd_in, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(txt_tgl_sppd, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kd_sppd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txt_no_sppd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_kd_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_tgl_sppd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_kendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_sppd_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel14)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_kodeadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_scan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kd_sppdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kd_sppdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kd_sppdActionPerformed

    private void txt_kd_pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kd_pegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kd_pegawaiActionPerformed

    private void txt_kendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kendaraanActionPerformed

    private void txt_biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_biayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_biayaActionPerformed

    private void txt_kodeadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodeadminActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            if (txt_kd_sppd.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Kode SPPD Belum Di Isi!");
                txt_kd_sppd.requestFocus();
            } else if (txt_no_sppd.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No SPPD Belum Di Isi!");
                txt_no_sppd.requestFocus();
            } else if (txt_kd_pegawai.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kode Pegawai Belum Di Isi!");
                txt_kd_pegawai.requestFocus();
            } else if (txt_tgl_sppd.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tanggal SPPD Belum Di Isi!");
                txt_tgl_sppd.requestFocus();
            } else if (txta_tempat.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tempat SPPD Belum Di Isi!");
                txta_tempat.requestFocus();
            } else if (txt_kendaraan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kendaraan SPPD Belum Di Isi!");
                txt_kendaraan.requestFocus();
            } else if (txt_biaya.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Biaya SPPD Belum Di Isi!");
                txt_biaya.requestFocus();
            } else if (txt_sppd_in.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tanggal Input SPPD Belum Di Isi!");
                txt_sppd_in.requestFocus();
            } else if (txt_kodeadmin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kode Admin Belum Di Isi!");
                txt_kodeadmin.requestFocus();
            } else if (txt_scan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Scan SPPD Belum Di Isi!");
                txt_scan.requestFocus();
            } else {
                String sqlCari = "SELECT * FROM tbl_sppd WHERE kd_sppd = ?";
                PreparedStatement cari = objekku.konekDB.prepareStatement(sqlCari);
                cari.setString(1, txt_kd_sppd.getText());
                ResultSet hasil = cari.executeQuery();
                if (hasil.next()){
                    JOptionPane.showMessageDialog(this, "Kode SPPD SUDAH ADA!");
                    txt_kd_sppd.setText(hasil.getString("kd_sppd"));
                    txt_no_sppd.setText(hasil.getString("no_sppd"));
                    txt_kd_pegawai.setText(hasil.getString("kd_pegawai"));
                    txt_tgl_sppd.setText(hasil.getString("tgl_sppd"));
                    txta_tempat.setText(hasil.getString("tempat_sppd"));
                    txt_kendaraan.setText(hasil.getString("kendaraan_sppd"));
                    txt_biaya.setText(hasil.getString("biaya_sppd"));
                    txt_sppd_in.setText(hasil.getString("tgl_inputsppd"));
                    txt_kodeadmin.setText(hasil.getString("kd_admin"));
                    txt_scan.setText(hasil.getString("scan_sppd"));
                } else {
                    String sqlSimpan = "INSERT INTO tbl_sppd VALUE (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement kueri = objekku.konekDB.prepareStatement(sqlSimpan);
                    
                    kueri.setString(1, txt_kd_sppd.getText());
                    kueri.setString(2, txt_no_sppd.getText());
                    kueri.setString(3, txt_kd_pegawai.getText());
                    kueri.setString(4, txt_tgl_sppd.getText());
                    kueri.setString(5, txta_tempat.getText());
                    kueri.setString(6, txt_kendaraan.getText());
                    kueri.setString(7, txt_biaya.getText());
                    kueri.setString(8, txt_sppd_in.getText());
                    kueri.setString(9, txt_kodeadmin.getText());
                    kueri.setString(10, txt_scan.getText());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            String sqlUbah = "UPDATE tbl_sddp SET no_sppd = ?, kd_pegawai = ?, tgl_sppd = ?, tempat_sppd = ?, kendaraan_sppd = ?, biaya_sppd = ? tgl_inputsppd = ?, kd_admin = ?, scan_sppd = ? WHERE kd_sppd = ?";
            PreparedStatement kueri = objekku.konekDB.prepareStatement(sqlUbah);
            
            kueri.setString(1, txt_kd_sppd.getText());
            kueri.setString(2, txt_no_sppd.getText());
            kueri.setString(3, txt_kd_pegawai.getText());
            kueri.setString(4, txt_tgl_sppd.getText());
            kueri.setString(5, txta_tempat.getText());
            kueri.setString(6, txt_kendaraan.getText());
            kueri.setString(7, txt_biaya.getText());
            kueri.setString(8, txt_sppd_in.getText());
            kueri.setString(9, txt_kodeadmin.getText());
            kueri.setString(10, txt_scan.getText());
            
            kueri.executeUpdate();
            loadTableSppd();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Ubah!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            String sqlHapus = "DELETE FROM tbl_sppd WHERE kd_sppd = ?";
            PreparedStatement kueri = objekku.konekDB.prepareStatement(sqlHapus);
            kueri.setString(1, txt_kd_sppd.getText());
        
            kueri.executeUpdate();
            loadTableSppd();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
 
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txt_scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_scanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_scanActionPerformed

    private void txt_no_sppdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_sppdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_sppdActionPerformed

    private void txt_tgl_sppdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tgl_sppdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tgl_sppdActionPerformed

    private void txt_sppd_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sppd_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sppd_inActionPerformed

    private void jTableSppdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSppdMouseClicked
        int i = jTableSppd.getSelectedRow();
        String kd_sppd = jTableSppd.getValueAt(i,0).toString();
        String no_sppd = jTableSppd.getValueAt(i,1).toString();
        String kd_pegawai = jTableSppd.getValueAt(i,2).toString();
        String tgl_sppd = jTableSppd.getValueAt(i,3).toString();
        String tempat_sppd = jTableSppd.getValueAt(i,4).toString();
        String kendaraan_sppd = jTableSppd.getValueAt(i,5).toString();
        String biaya_sppd = jTableSppd.getValueAt(i,6).toString();
        String tgl_inputppd = jTableSppd.getValueAt(i,7).toString();
        String kd_admin = jTableSppd.getValueAt(i,8).toString();
        String scan_sppd = jTableSppd.getValueAt(i,9).toString();
        
        txt_kd_sppd.setText(kd_sppd);
        txt_no_sppd.setText(no_sppd);
        txt_kd_pegawai.setText(kd_pegawai);
        txt_tgl_sppd.setText(tgl_sppd);
        txta_tempat.setText(tempat_sppd);
        txt_kendaraan.setText(kendaraan_sppd);
        txt_biaya.setText(biaya_sppd);
        txt_sppd_in.setText(tgl_inputppd);
        txt_kodeadmin.setText(kd_admin);
        txt_scan.setText(scan_sppd);
    }//GEN-LAST:event_jTableSppdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameSppd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameSppd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameSppd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameSppd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameSppd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableSppd;
    private javax.swing.JTextField txt_biaya;
    private javax.swing.JTextField txt_kd_pegawai;
    private javax.swing.JTextField txt_kd_sppd;
    private javax.swing.JTextField txt_kendaraan;
    private javax.swing.JTextField txt_kodeadmin;
    private javax.swing.JTextField txt_no_sppd;
    private javax.swing.JTextField txt_scan;
    private javax.swing.JTextField txt_sppd_in;
    private javax.swing.JTextField txt_tgl_sppd;
    private javax.swing.JTextArea txta_tempat;
    // End of variables declaration//GEN-END:variables
}
