/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import dataBase.configdb_2110010302;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator 10
 */
public class frameSppd extends javax.swing.JFrame {
    configdb_2110010302 obj;
    
    public void tampilDataSppd(){
        String[] JudulKolom = {"Kode", "No SPPD", "Kode Pegawai", "Tanggal", "Tempat", "Kendaraan", "Biaya", "Tgl Input", "Kode Admin", "Scan"}; //kolom yang akan di tampilkan
        int[] lebar ={50, 50, 75, 100, 150, 100, 100, 100, 50, 75}; //lebar masing-masing kolom
        String query = "SELECT * FROM tbl_sppd";
        obj.JudulJTable(jTableSppd, JudulKolom); //judul kolom
        obj.tampilTable(JudulKolom, query, jTableSppd); //isi tabel
        obj.LebarJtable(jTableSppd, lebar); //lebar kolom
        lblJmlData.setText(String.valueOf(obj.jumlahRecord(query)));
    }
    
    public frameSppd() {
        initComponents();
        this.setLocationRelativeTo(null);
        obj = new configdb_2110010302();
        tampilDataSppd();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_kd_sppd = new javax.swing.JTextField();
        txt_kd_pegawai = new javax.swing.JTextField();
        txt_kendaraan = new javax.swing.JTextField();
        txt_biaya = new javax.swing.JTextField();
        txt_kodeadmin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSppd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_tempat = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txt_scan = new javax.swing.JTextField();
        txt_no_sppd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_tgl_sppd = new javax.swing.JTextField();
        txt_sppd_in = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblJmlData = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("kode SPPD");

        jLabel2.setText("nomor SPPD");

        jLabel3.setText("kode pegawai");

        jLabel4.setText("tanggal SPPD");

        jLabel5.setText("tempat SPPD");

        jLabel6.setText("kendaraan SPPD");

        jLabel7.setText("biaya SPPD");

        jLabel8.setText("tanggal input SPPD");

        jLabel9.setText("kode admin");

        jLabel10.setText("scan SPPD");

        txt_kd_sppd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kd_sppdActionPerformed(evt);
            }
        });

        txt_kd_pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kd_pegawaiActionPerformed(evt);
            }
        });

        txt_kendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kendaraanActionPerformed(evt);
            }
        });

        txt_biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_biayaActionPerformed(evt);
            }
        });

        txt_kodeadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeadminActionPerformed(evt);
            }
        });

        jTableSppd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kode", "nomor", "kode pegawai", "tanggal", "tempat", "kendaraan", "biaya", "tanggal input", "kode admin", "scan"
            }
        ));
        jTableSppd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSppdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSppd);

        txta_tempat.setColumns(20);
        txta_tempat.setRows(5);
        jScrollPane2.setViewportView(txta_tempat);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txt_scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_scanActionPerformed(evt);
            }
        });

        txt_no_sppd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_sppdActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel13.setText("*dalam format tahun-bulan-tanggal (tttt-bb-hh)");

        txt_tgl_sppd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tgl_sppdActionPerformed(evt);
            }
        });

        txt_sppd_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sppd_inActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel14.setText("*dalam format tahun-bulan-tanggal (tttt-bb-hh)");

        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setText("JUMLAH DATA:");

        lblJmlData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJmlData.setText("\"\"");

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        jLabel12.setText("CARI DATA");

        jReport.setText("REPORT");
        jReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(81, 81, 81)
                                        .addComponent(txt_scan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(txt_kodeadmin)
                                                    .addComponent(txt_biaya)
                                                    .addComponent(txt_kendaraan)
                                                    .addComponent(txt_kd_pegawai)
                                                    .addComponent(txt_kd_sppd)
                                                    .addComponent(txt_no_sppd, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_sppd_in, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(txt_tgl_sppd, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblJmlData))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCari))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus))
                            .addComponent(jReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kd_sppd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txt_no_sppd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_kd_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_tgl_sppd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_kendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_sppd_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_kodeadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_scan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblJmlData))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jReport))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kd_sppdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kd_sppdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kd_sppdActionPerformed

    private void txt_kd_pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kd_pegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kd_pegawaiActionPerformed

    private void txt_kendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kendaraanActionPerformed

    private void txt_biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_biayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_biayaActionPerformed

    private void txt_kodeadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodeadminActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            String[] FieldTabelnya ={"kd_sppd", "no_sppd", "kd_pegawai", "tgl_sppd", "tempat_sppd", "kendaraan_sppd", "biaya_sppd", "tgl_inputsppd", "kd_admin", "scan_sppd"};
            String[] Isitabelnya = {txt_kd_sppd.getText(), txt_no_sppd.getText(), txt_kd_pegawai.getText(), txt_tgl_sppd.getText(), txta_tempat.getText(), txt_kendaraan.getText(), txt_biaya.getText(), txt_sppd_in.getText(), txt_kodeadmin.getText(), txt_scan.getText()};
            String NamaTabel = "tbl_sppd";
            if (txt_kd_sppd.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Kode SPPD Belum Di Isi!");
                txt_kd_sppd.requestFocus();
            } else if (txt_no_sppd.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No SPPD Belum Di Isi!");
                txt_no_sppd.requestFocus();
            } else if (txt_kd_pegawai.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kode Pegawai Belum Di Isi!");
                txt_kd_pegawai.requestFocus();
            } else if (txt_tgl_sppd.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tanggal SPPD Belum Di Isi!");
                txt_tgl_sppd.requestFocus();
            } else if (txta_tempat.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tempat SPPD Belum Di Isi!");
                txta_tempat.requestFocus();
            } else if (txt_kendaraan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kendaraan SPPD Belum Di Isi!");
                txt_kendaraan.requestFocus();
            } else if (txt_biaya.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Biaya SPPD Belum Di Isi!");
                txt_biaya.requestFocus();
            } else if (txt_sppd_in.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tanggal Input SPPD Belum Di Isi!");
                txt_sppd_in.requestFocus();
            } else if (txt_kodeadmin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kode Admin Belum Di Isi!");
                txt_kodeadmin.requestFocus();
            } else if (txt_scan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Scan SPPD Belum Di Isi!");
                txt_scan.requestFocus();
            } else if (obj.duplikasiKey(NamaTabel, NamaTabel, NamaTabel)){
                try {
                    Statement stm = obj.getKoneksi().createStatement();
                    ResultSet rslt = stm.executeQuery("SELECT * FROM tbl_sppd WHERE kd_admin = "+txt_kd_sppd.getText());
                    rslt.next();
                    txt_kd_sppd.setText(rslt.getString(2));
                    txt_no_sppd.setText(rslt.getString(3));
                    txt_kd_pegawai.setText(rslt.getString(4));
                    txt_tgl_sppd.setText(rslt.getString(5));
                    txta_tempat.setText(rslt.getString(6));
                    txt_kendaraan.setText(rslt.getString(7));
                    txt_biaya.setText(rslt.getString(8));
                    txt_sppd_in.setText(rslt.getString(8));
                    txt_kodeadmin.setText(rslt.getString(10));
                    txt_scan.setText(rslt.getString(11));                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.toString());
                }
            } else {
                obj.simpanDBAuto(NamaTabel, FieldTabelnya, Isitabelnya);
                tampilDataSppd();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Simpan, YAY!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            if ((txt_kd_sppd.getText().isEmpty()) && (txt_no_sppd.getText().isEmpty()) && (txt_kd_pegawai.getText().isEmpty()) && (txt_tgl_sppd.getText().isEmpty()) && (txta_tempat.getText().isEmpty()) && (txt_kendaraan.getText().isEmpty()) && (txt_biaya.getText().isEmpty()) && (txt_sppd_in.getText().isEmpty()) && (txt_kodeadmin.getText().isEmpty()) && (txt_scan.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu!");
                jTableSppd.requestFocus();
            } else {
                String[] FieldTabelnya ={"no_sppd", "kd_pegawai", "tgl_sppd", "tempat_sppd", "kendaraan_sppd", "biaya_sppd", "tgl_inputsppd", "kd_admin", "scan_sppd"};
                String[] Isitabelnya = {txt_no_sppd.getText(), txt_kd_pegawai.getText(), txt_tgl_sppd.getText(), txta_tempat.getText(), txt_kendaraan.getText(), txt_biaya.getText(), txt_sppd_in.getText(), txt_kodeadmin.getText(), txt_scan.getText()};
                String NamaTabel = "tbl_sppd";
                String kd_key = txt_kd_sppd.getText();
                obj.UbahDBAuto(NamaTabel, "kd_sppd", kd_key, FieldTabelnya, Isitabelnya);
                tampilDataSppd();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Ubah!");
            }
            JOptionPane.showMessageDialog(this, "Data Berhasil di Ubah!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            if ((txt_kd_sppd.getText().isEmpty()) && (txt_no_sppd.getText().isEmpty()) && (txt_kd_pegawai.getText().isEmpty()) && (txt_tgl_sppd.getText().isEmpty()) && (txta_tempat.getText().isEmpty()) && (txt_kendaraan.getText().isEmpty()) && (txt_biaya.getText().isEmpty()) && (txt_sppd_in.getText().isEmpty()) && (txt_kodeadmin.getText().isEmpty()) && (txt_scan.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Akan Di Hapus Terlebih Dahulu!");
                jTableSppd.requestFocus();
            } else {
                String NamaTabel = "tbl_sppd";
                String kd_key = txt_kd_sppd.getText();
                obj.HapusDBAuto(NamaTabel, "kd_sppd", kd_key);
                tampilDataSppd();
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
 
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txt_scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_scanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_scanActionPerformed

    private void txt_no_sppdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_sppdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_sppdActionPerformed

    private void txt_tgl_sppdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tgl_sppdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tgl_sppdActionPerformed

    private void txt_sppd_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sppd_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sppd_inActionPerformed

    private void jTableSppdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSppdMouseClicked
        int i = jTableSppd.getSelectedRow();
        String kd_sppd = jTableSppd.getValueAt(i,0).toString();
        String no_sppd = jTableSppd.getValueAt(i,1).toString();
        String kd_pegawai = jTableSppd.getValueAt(i,2).toString();
        String tgl_sppd = jTableSppd.getValueAt(i,3).toString();
        String tempat_sppd = jTableSppd.getValueAt(i,4).toString();
        String kendaraan_sppd = jTableSppd.getValueAt(i,5).toString();
        String biaya_sppd = jTableSppd.getValueAt(i,6).toString();
        String tgl_inputppd = jTableSppd.getValueAt(i,7).toString();
        String kd_admin = jTableSppd.getValueAt(i,8).toString();
        String scan_sppd = jTableSppd.getValueAt(i,9).toString();
        
        txt_kd_sppd.setText(kd_sppd);
        txt_no_sppd.setText(no_sppd);
        txt_kd_pegawai.setText(kd_pegawai);
        txt_tgl_sppd.setText(tgl_sppd);
        txta_tempat.setText(tempat_sppd);
        txt_kendaraan.setText(kendaraan_sppd);
        txt_biaya.setText(biaya_sppd);
        txt_sppd_in.setText(tgl_inputppd);
        txt_kodeadmin.setText(kd_admin);
        txt_scan.setText(scan_sppd);
    }//GEN-LAST:event_jTableSppdMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String clear = "";
        txt_kd_sppd.setText(clear);
        txt_no_sppd.setText(clear);
        txt_kd_pegawai.setText(clear);
        txt_tgl_sppd.setText(clear);
        txta_tempat.setText(clear);
        txt_kendaraan.setText(clear);
        txt_biaya.setText(clear);
        txt_sppd_in.setText(clear);
        txt_kodeadmin.setText(clear);
        txt_scan.setText(clear);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        try {
            String cari = txtCari.getText();
            String query =  "SELECT * FROM tbl_sppd WHERE kd_sppd LIKE '%" + cari + "%' OR " +
                            "no_sppd LIKE '%" + cari + "%' OR " +
                            "kd_pegawai LIKE '%" + cari + "%' OR " +
                            "tempat_sppd LIKE '%" + cari + "%' OR " +
                            "kendaraan_sppd LIKE '%" + cari + "%' OR " +
                            "biaya_sppd LIKE '%" + cari + "%' OR " +
                            "kd_admin LIKE '%" + cari + "%' OR " +
                            "scan_sppd LIKE '%" + cari + "%'";
            
            String[] JudulKolom = {"Kode", "No SPPD", "Kode Pegawai", "Tanggal", "Tempat", "Kendaraan", "Biaya", "Tgl Input", "Kode Admin", "Scan"}; //kolom yang akan di tampilkan
            int[] lebar ={50, 50, 75, 100, 150, 100, 100, 100, 50, 75}; //lebar masing-masing kolom
            obj.JudulJTable(jTableSppd, JudulKolom); //judul kolom
            obj.tampilTable(JudulKolom, query, jTableSppd); //isi tabel
            obj.LebarJtable(jTableSppd, lebar); //lebar kolom

        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_txtCariKeyPressed

    private void jReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReportActionPerformed
        String cari = txtCari.getText();
        String SQL = "SELECT * FROM tbl_admin WHERE kd_admin LIKE '%"+cari+"%' OR nama_admin LIKE '%"+cari+"%' OR username_admin LIKE '%"+cari+"%'";
        obj.tampilLaporan("src/report/lapAdmin.jrxml", SQL);
    }//GEN-LAST:event_jReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameSppd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameSppd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameSppd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameSppd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameSppd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableSppd;
    private javax.swing.JLabel lblJmlData;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txt_biaya;
    private javax.swing.JTextField txt_kd_pegawai;
    private javax.swing.JTextField txt_kd_sppd;
    private javax.swing.JTextField txt_kendaraan;
    private javax.swing.JTextField txt_kodeadmin;
    private javax.swing.JTextField txt_no_sppd;
    private javax.swing.JTextField txt_scan;
    private javax.swing.JTextField txt_sppd_in;
    private javax.swing.JTextField txt_tgl_sppd;
    private javax.swing.JTextArea txta_tempat;
    // End of variables declaration//GEN-END:variables
}
